import { FirstAidCategory } from '@/types';

export const FIRST_AID_CATEGORIES: FirstAidCategory[] = [
  {
    id: '1',
    title: 'Burns',
    description: 'Treatment for minor and major burns',
    icon: 'fire',
    steps: [
      'Remove the person from the source of heat',
      'Cool the burn with cool or lukewarm running water for 10-20 minutes',
      'Remove any clothing or jewelry near the burn (unless stuck to skin)',
      'Cover the burn with a sterile, non-adhesive bandage',
      'Take over-the-counter pain medication if needed',
      'Seek medical attention for severe burns',
    ],
  },
  {
    id: '2',
    title: 'Cuts and Bleeding',
    description: 'How to treat cuts and control bleeding',
    icon: 'droplet',
    steps: [
      'Wash your hands thoroughly',
      'Apply direct pressure to the wound with a clean cloth',
      'Elevate the injured area above the heart if possible',
      'Clean the wound gently with water',
      'Apply antibiotic ointment if available',
      'Cover with a sterile bandage',
      'Change the bandage daily and keep the wound clean',
    ],
  },
  {
    id: '3',
    title: 'Fractures',
    description: 'First aid for broken bones',
    icon: 'bone',
    steps: [
      'Do not move the person unless they are in immediate danger',
      'Immobilize the injured area',
      'Apply ice wrapped in a cloth to reduce swelling',
      'Check for circulation below the injury',
      'Cover any open wounds with sterile bandages',
      'Get emergency medical help immediately',
      'Monitor for signs of shock',
    ],
  },
  {
    id: '4',
    title: 'Choking',
    description: 'Emergency response for choking victims',
    icon: 'alert-triangle',
    steps: [
      'Encourage the person to cough forcefully',
      'Give 5 back blows between the shoulder blades',
      'Give 5 abdominal thrusts (Heimlich maneuver)',
      'Alternate between back blows and abdominal thrusts',
      'Call emergency services if the object is not dislodged',
      'Continue until help arrives or the person becomes unconscious',
    ],
  },
  {
    id: '5',
    title: 'Heart Attack',
    description: 'Recognizing and responding to heart attacks',
    icon: 'heart',
    steps: [
      'Call emergency services immediately',
      'Help the person sit down and rest',
      'Loosen any tight clothing',
      'Give aspirin if the person is not allergic and conscious',
      'Monitor breathing and pulse',
      'Be prepared to perform CPR if necessary',
      'Stay with the person until help arrives',
    ],
  },
  {
    id: '6',
    title: 'Allergic Reactions',
    description: 'Managing mild to severe allergic reactions',
    icon: 'shield-alert',
    steps: [
      'Remove or avoid the allergen if known',
      'For mild reactions, give antihistamines',
      'For severe reactions (anaphylaxis), use epinephrine auto-injector',
      'Call emergency services for severe reactions',
      'Help the person lie down with legs elevated',
      'Monitor breathing and consciousness',
      'Be prepared to perform CPR if needed',
    ],
  },
  {
  id: '7',
  title: 'Nosebleeds',
  description: 'Steps to stop a nosebleed quickly and safely',
  icon: 'wind',
  steps: [
    'Sit the person upright and lean them forward slightly',
    'Pinch the soft part of the nose just below the bridge',
    'Maintain pressure for 10–15 minutes without releasing',
    'Apply a cold compress to the nose and cheeks',
    'Avoid blowing or picking the nose afterward',
    'Seek medical help if bleeding lasts more than 20 minutes',
  ],
},
{
  id: '8',
  title: 'Fainting',
  description: 'How to respond when someone faints',
  icon: 'activity',
  steps: [
    'Lay the person flat on their back',
    'Elevate their legs to improve blood flow',
    'Loosen tight clothing',
    'Check for breathing and pulse',
    'Do not give anything to eat or drink immediately',
    'Seek medical help if they do not regain consciousness quickly',
  ],
},
{
  id: '9',
  title: 'Sprains and Strains',
  description: 'Initial care for muscle and joint injuries',
  icon: 'move',
  steps: [
    'Rest the injured area',
    'Apply ice wrapped in a cloth for 15-20 minutes',
    'Compress with an elastic bandage',
    'Elevate the injured area above heart level',
    'Avoid using the injured part until pain and swelling decrease',
    'Seek medical attention if there is severe pain or instability',
  ],
},
{
  id: '10',
  title: 'Poisoning',
  description: 'Emergency actions for suspected poisoning',
  icon: 'biohazard',
  steps: [
    'Call emergency services or poison control immediately',
    'Do not induce vomiting unless advised by professionals',
    'If the poison is on the skin, rinse with running water for 15 minutes',
    'If inhaled, move the person to fresh air',
    'Provide the poison label or container to emergency responders',
    'Monitor breathing and consciousness',
  ],
},
{
  id: '11',
  title: 'Seizures',
  description: 'What to do during and after a seizure',
  icon: 'zap',
  steps: [
    'Stay calm and keep others away',
    'Protect the person from injury by moving harmful objects',
    'Do not restrain the person',
    'Do not put anything in their mouth',
    'After seizure, help them to rest on their side',
    'Call emergency services if seizure lasts over 5 minutes',
  ],
},
{
  id: '12',
  title: 'Eye Injuries',
  description: 'First aid for eye irritations or injuries',
  icon: 'eye',
  steps: [
    'Do not rub the eye',
    'Flush with clean water or saline if a chemical or foreign object is present',
    'Do not attempt to remove embedded objects',
    'Cover both eyes to reduce movement',
    'Seek emergency medical attention',
  ],
},
{
  id: '13',
  title: 'Insect Bites & Stings',
  description: 'Managing pain and reactions from bites or stings',
  icon: 'bug',
  steps: [
    'Move away from the insect area',
    'Remove stinger if visible by scraping (not with tweezers)',
    'Clean the area with soap and water',
    'Apply a cold pack to reduce swelling',
    'Use antihistamines or creams for itching',
    'Seek emergency help if signs of allergic reaction occur',
  ],
},
{
  id: '14',
  title: 'Heatstroke',
  description: 'Emergency care for heat-related illness',
  icon: 'thermometer',
  steps: [
    'Move the person to a cooler place immediately',
    'Remove excess clothing',
    'Cool the body with wet cloths or cold water',
    'Fan the person to increase cooling',
    'Give small sips of water if conscious',
    'Call emergency services immediately',
  ],
},
{
  id: '15',
  title: 'Hypothermia',
  description: 'Care for cold-related emergencies',
  icon: 'snowflake',
  steps: [
    'Move the person to a warm environment',
    'Remove any wet clothing and replace with warm, dry layers',
    'Wrap in blankets, especially head and neck',
    'Give warm (not hot) drinks if conscious',
    'Do not apply direct heat or massage limbs',
    'Call emergency help immediately',
  ],
}
];