import { Language } from '@/types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to RAHA Health',
    selectLanguage: 'Select Your Language',
    continue: 'Continue',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    dashboard: 'Dashboard',
    symptomChecker: 'Symptom Checker',
    firstAid: 'First Aid Guide',
    medicineReminder: 'Medicine Reminder',
    voiceAssistant: 'Voice Assistant',
    nearbyHospitals: 'Nearby Hospitals',
    settings: 'Settings',
    logout: 'Logout',
    hello: 'Hello',
    howCanIHelp: 'How can I help you today?',
  },
  hi: {
    welcome: 'राहा हेल्थ में आपका स्वागत है',
    selectLanguage: 'अपनी भाषा चुनें',
    continue: 'जारी रखें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    dashboard: 'डैशबोर्ड',
    symptomChecker: 'लक्षण जांचकर्ता',
    firstAid: 'प्राथमिक चिकित्सा गाइड',
    medicineReminder: 'दवा रिमाइंडर',
    voiceAssistant: 'वॉयस असिस्टेंट',
    nearbyHospitals: 'नजदीकी अस्पताल',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    hello: 'नमस्ते',
    howCanIHelp: 'आज मैं आपकी कैसे मदद कर सकता हूं?',
  },
};